# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('13.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end

target 'UHShield' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UHShield
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
end
